# Generated by Django 2.2.12 on 2020-05-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Producttype')),
            ],
        ),
    ]
